/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as JoueursRouteImport } from './routes/joueurs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppJoueursRouteImport } from './routes/app/joueurs'
import { Route as AppParametresRouteImport } from './routes/app/parametres'
import { Route as AppStatistiquesRouteImport } from './routes/app/statistiques'
import { Route as ConcoursIndexRouteImport } from './routes/concours/index'
import { Route as ConcoursIdRouteRouteImport } from './routes/concours/$id/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppConcoursIndexRouteImport } from './routes/app/concours/index'
import { Route as AppConcoursIdRouteImport } from './routes/app/concours/$id'
import { Route as AppConcoursNouveauRouteImport } from './routes/app/concours/nouveau'
import { Route as ConcoursIdIndexRouteImport } from './routes/concours/$id/index'
import { Route as ConcoursIdClassementRouteImport } from './routes/concours/$id/classement'
import { Route as ConcoursIdLiveRouteImport } from './routes/concours/$id/live'
import { Route as ConcoursIdMatchsRouteImport } from './routes/concours/$id/matchs'
import { Route as ConcoursIdPoulesRouteImport } from './routes/concours/$id/poules'
import { Route as ConcoursIdTableauRouteImport } from './routes/concours/$id/tableau'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const JoueursRoute = JoueursRouteImport.update({
  id: '/joueurs',
  path: '/joueurs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppJoueursRoute = AppJoueursRouteImport.update({
  id: '/joueurs',
  path: '/joueurs',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppParametresRoute = AppParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStatistiquesRoute = AppStatistiquesRouteImport.update({
  id: '/statistiques',
  path: '/statistiques',
  getParentRoute: () => AppRouteRoute,
} as any)
const ConcoursIndexRoute = ConcoursIndexRouteImport.update({
  id: '/concours/',
  path: '/concours/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcoursIdRouteRoute = ConcoursIdRouteRouteImport.update({
  id: '/concours/$id',
  path: '/concours/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppConcoursIndexRoute = AppConcoursIndexRouteImport.update({
  id: '/concours/',
  path: '/concours/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppConcoursIdRoute = AppConcoursIdRouteImport.update({
  id: '/concours/$id',
  path: '/concours/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppConcoursNouveauRoute = AppConcoursNouveauRouteImport.update({
  id: '/concours/nouveau',
  path: '/concours/nouveau',
  getParentRoute: () => AppRouteRoute,
} as any)
const ConcoursIdIndexRoute = ConcoursIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConcoursIdRouteRoute,
} as any)
const ConcoursIdClassementRoute = ConcoursIdClassementRouteImport.update({
  id: '/classement',
  path: '/classement',
  getParentRoute: () => ConcoursIdRouteRoute,
} as any)
const ConcoursIdLiveRoute = ConcoursIdLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => ConcoursIdRouteRoute,
} as any)
const ConcoursIdMatchsRoute = ConcoursIdMatchsRouteImport.update({
  id: '/matchs',
  path: '/matchs',
  getParentRoute: () => ConcoursIdRouteRoute,
} as any)
const ConcoursIdPoulesRoute = ConcoursIdPoulesRouteImport.update({
  id: '/poules',
  path: '/poules',
  getParentRoute: () => ConcoursIdRouteRoute,
} as any)
const ConcoursIdTableauRoute = ConcoursIdTableauRouteImport.update({
  id: '/tableau',
  path: '/tableau',
  getParentRoute: () => ConcoursIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/joueurs': typeof JoueursRoute
  '/login': typeof LoginRoute
  '/concours/$id': typeof ConcoursIdRouteRouteWithChildren
  '/app/joueurs': typeof AppJoueursRoute
  '/app/parametres': typeof AppParametresRoute
  '/app/statistiques': typeof AppStatistiquesRoute
  '/app/': typeof AppIndexRoute
  '/concours/': typeof ConcoursIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/concours/$id': typeof AppConcoursIdRoute
  '/app/concours/nouveau': typeof AppConcoursNouveauRoute
  '/concours/$id/classement': typeof ConcoursIdClassementRoute
  '/concours/$id/live': typeof ConcoursIdLiveRoute
  '/concours/$id/matchs': typeof ConcoursIdMatchsRoute
  '/concours/$id/poules': typeof ConcoursIdPoulesRoute
  '/concours/$id/tableau': typeof ConcoursIdTableauRoute
  '/app/concours/': typeof AppConcoursIndexRoute
  '/concours/$id/': typeof ConcoursIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/joueurs': typeof JoueursRoute
  '/login': typeof LoginRoute
  '/app/joueurs': typeof AppJoueursRoute
  '/app/parametres': typeof AppParametresRoute
  '/app/statistiques': typeof AppStatistiquesRoute
  '/app': typeof AppIndexRoute
  '/concours': typeof ConcoursIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/concours/$id': typeof AppConcoursIdRoute
  '/app/concours/nouveau': typeof AppConcoursNouveauRoute
  '/concours/$id/classement': typeof ConcoursIdClassementRoute
  '/concours/$id/live': typeof ConcoursIdLiveRoute
  '/concours/$id/matchs': typeof ConcoursIdMatchsRoute
  '/concours/$id/poules': typeof ConcoursIdPoulesRoute
  '/concours/$id/tableau': typeof ConcoursIdTableauRoute
  '/app/concours': typeof AppConcoursIndexRoute
  '/concours/$id': typeof ConcoursIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/joueurs': typeof JoueursRoute
  '/login': typeof LoginRoute
  '/concours/$id': typeof ConcoursIdRouteRouteWithChildren
  '/app/joueurs': typeof AppJoueursRoute
  '/app/parametres': typeof AppParametresRoute
  '/app/statistiques': typeof AppStatistiquesRoute
  '/app/': typeof AppIndexRoute
  '/concours/': typeof ConcoursIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/concours/$id': typeof AppConcoursIdRoute
  '/app/concours/nouveau': typeof AppConcoursNouveauRoute
  '/concours/$id/classement': typeof ConcoursIdClassementRoute
  '/concours/$id/live': typeof ConcoursIdLiveRoute
  '/concours/$id/matchs': typeof ConcoursIdMatchsRoute
  '/concours/$id/poules': typeof ConcoursIdPoulesRoute
  '/concours/$id/tableau': typeof ConcoursIdTableauRoute
  '/app/concours/': typeof AppConcoursIndexRoute
  '/concours/$id/': typeof ConcoursIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/joueurs'
    | '/login'
    | '/concours/$id'
    | '/app/joueurs'
    | '/app/parametres'
    | '/app/statistiques'
    | '/app/'
    | '/concours/'
    | '/api/auth/$'
    | '/app/concours/$id'
    | '/app/concours/nouveau'
    | '/concours/$id/classement'
    | '/concours/$id/live'
    | '/concours/$id/matchs'
    | '/concours/$id/poules'
    | '/concours/$id/tableau'
    | '/app/concours/'
    | '/concours/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/joueurs'
    | '/login'
    | '/app/joueurs'
    | '/app/parametres'
    | '/app/statistiques'
    | '/app'
    | '/concours'
    | '/api/auth/$'
    | '/app/concours/$id'
    | '/app/concours/nouveau'
    | '/concours/$id/classement'
    | '/concours/$id/live'
    | '/concours/$id/matchs'
    | '/concours/$id/poules'
    | '/concours/$id/tableau'
    | '/app/concours'
    | '/concours/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/joueurs'
    | '/login'
    | '/concours/$id'
    | '/app/joueurs'
    | '/app/parametres'
    | '/app/statistiques'
    | '/app/'
    | '/concours/'
    | '/api/auth/$'
    | '/app/concours/$id'
    | '/app/concours/nouveau'
    | '/concours/$id/classement'
    | '/concours/$id/live'
    | '/concours/$id/matchs'
    | '/concours/$id/poules'
    | '/concours/$id/tableau'
    | '/app/concours/'
    | '/concours/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  JoueursRoute: typeof JoueursRoute
  LoginRoute: typeof LoginRoute
  ConcoursIdRouteRoute: typeof ConcoursIdRouteRouteWithChildren
  ConcoursIndexRoute: typeof ConcoursIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joueurs': {
      id: '/joueurs'
      path: '/joueurs'
      fullPath: '/joueurs'
      preLoaderRoute: typeof JoueursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/joueurs': {
      id: '/app/joueurs'
      path: '/joueurs'
      fullPath: '/app/joueurs'
      preLoaderRoute: typeof AppJoueursRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/parametres': {
      id: '/app/parametres'
      path: '/parametres'
      fullPath: '/app/parametres'
      preLoaderRoute: typeof AppParametresRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/statistiques': {
      id: '/app/statistiques'
      path: '/statistiques'
      fullPath: '/app/statistiques'
      preLoaderRoute: typeof AppStatistiquesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/concours/': {
      id: '/concours/'
      path: '/concours'
      fullPath: '/concours/'
      preLoaderRoute: typeof ConcoursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concours/$id': {
      id: '/concours/$id'
      path: '/concours/$id'
      fullPath: '/concours/$id'
      preLoaderRoute: typeof ConcoursIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/concours/': {
      id: '/app/concours/'
      path: '/concours'
      fullPath: '/app/concours/'
      preLoaderRoute: typeof AppConcoursIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/concours/$id': {
      id: '/app/concours/$id'
      path: '/concours/$id'
      fullPath: '/app/concours/$id'
      preLoaderRoute: typeof AppConcoursIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/concours/nouveau': {
      id: '/app/concours/nouveau'
      path: '/concours/nouveau'
      fullPath: '/app/concours/nouveau'
      preLoaderRoute: typeof AppConcoursNouveauRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/concours/$id/': {
      id: '/concours/$id/'
      path: '/'
      fullPath: '/concours/$id/'
      preLoaderRoute: typeof ConcoursIdIndexRouteImport
      parentRoute: typeof ConcoursIdRouteRoute
    }
    '/concours/$id/classement': {
      id: '/concours/$id/classement'
      path: '/classement'
      fullPath: '/concours/$id/classement'
      preLoaderRoute: typeof ConcoursIdClassementRouteImport
      parentRoute: typeof ConcoursIdRouteRoute
    }
    '/concours/$id/live': {
      id: '/concours/$id/live'
      path: '/live'
      fullPath: '/concours/$id/live'
      preLoaderRoute: typeof ConcoursIdLiveRouteImport
      parentRoute: typeof ConcoursIdRouteRoute
    }
    '/concours/$id/matchs': {
      id: '/concours/$id/matchs'
      path: '/matchs'
      fullPath: '/concours/$id/matchs'
      preLoaderRoute: typeof ConcoursIdMatchsRouteImport
      parentRoute: typeof ConcoursIdRouteRoute
    }
    '/concours/$id/poules': {
      id: '/concours/$id/poules'
      path: '/poules'
      fullPath: '/concours/$id/poules'
      preLoaderRoute: typeof ConcoursIdPoulesRouteImport
      parentRoute: typeof ConcoursIdRouteRoute
    }
    '/concours/$id/tableau': {
      id: '/concours/$id/tableau'
      path: '/tableau'
      fullPath: '/concours/$id/tableau'
      preLoaderRoute: typeof ConcoursIdTableauRouteImport
      parentRoute: typeof ConcoursIdRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppJoueursRoute: typeof AppJoueursRoute
  AppParametresRoute: typeof AppParametresRoute
  AppStatistiquesRoute: typeof AppStatistiquesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppConcoursIdRoute: typeof AppConcoursIdRoute
  AppConcoursNouveauRoute: typeof AppConcoursNouveauRoute
  AppConcoursIndexRoute: typeof AppConcoursIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppJoueursRoute: AppJoueursRoute,
  AppParametresRoute: AppParametresRoute,
  AppStatistiquesRoute: AppStatistiquesRoute,
  AppIndexRoute: AppIndexRoute,
  AppConcoursIdRoute: AppConcoursIdRoute,
  AppConcoursNouveauRoute: AppConcoursNouveauRoute,
  AppConcoursIndexRoute: AppConcoursIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface ConcoursIdRouteRouteChildren {
  ConcoursIdClassementRoute: typeof ConcoursIdClassementRoute
  ConcoursIdLiveRoute: typeof ConcoursIdLiveRoute
  ConcoursIdMatchsRoute: typeof ConcoursIdMatchsRoute
  ConcoursIdPoulesRoute: typeof ConcoursIdPoulesRoute
  ConcoursIdTableauRoute: typeof ConcoursIdTableauRoute
  ConcoursIdIndexRoute: typeof ConcoursIdIndexRoute
}

const ConcoursIdRouteRouteChildren: ConcoursIdRouteRouteChildren = {
  ConcoursIdClassementRoute: ConcoursIdClassementRoute,
  ConcoursIdLiveRoute: ConcoursIdLiveRoute,
  ConcoursIdMatchsRoute: ConcoursIdMatchsRoute,
  ConcoursIdPoulesRoute: ConcoursIdPoulesRoute,
  ConcoursIdTableauRoute: ConcoursIdTableauRoute,
  ConcoursIdIndexRoute: ConcoursIdIndexRoute,
}

const ConcoursIdRouteRouteWithChildren = ConcoursIdRouteRoute._addFileChildren(
  ConcoursIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  JoueursRoute: JoueursRoute,
  LoginRoute: LoginRoute,
  ConcoursIdRouteRoute: ConcoursIdRouteRouteWithChildren,
  ConcoursIndexRoute: ConcoursIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
